spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phoneshop
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    
    
#spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: 
#  h2:
#    console:
#      enabled: true
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create
     
