spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phoneshop
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
     
